from enum import Enum
class modelType(Enum):
    DECISION_TREE_GINI_CLASSIFIER = 1
    DECISION_TREE_ENTROPHY_CLASSIFIER = 2
    RANDOM_FOREST_CLASSIFIER = 3
    RANDOM_FOREST_REGRESSOR = 4
    DECISION_TREE_GINI_REGRESSOR = 5
    DECISION_TREE_ENTROPHY_REGRESSOR = 6
    ADA_BOOST_REGRESSOR = 7
    ADA_BOOST_CLASSIFIER = 8
    GRADIENT_BOOSTING_REGRESSOR = 9
    GRADIENT_BOOSTING_CLASSIFIER = 10
    MODEL5 = 11
    MODEL6 = 12
    MODEL7 = 13
